set(MIN_NODE_VERSION "14.00.0")

# Clean up directory
message(STATUS "PYTHON_PACKAGE_SRC_DIR: ${PYTHON_PACKAGE_SRC_DIR}")
message(STATUS "PYTHON_PACKAGE_DST_DIR: ${PYTHON_PACKAGE_DST_DIR}")
file(REMOVE_RECURSE ${PYTHON_PACKAGE_DST_DIR})
file(COPY ${PYTHON_PACKAGE_SRC_DIR}/ DESTINATION ${PYTHON_PACKAGE_DST_DIR}/)
configure_file("${PYTHON_PACKAGE_DST_DIR}/setup.py" "${PYTHON_PACKAGE_DST_DIR}/setup.py")
configure_file("${PYTHON_PACKAGE_DST_DIR}/pydock/__init__.py" "${PYTHON_PACKAGE_DST_DIR}/pydock/__init__.py")
file(COPY "${PYTHON_COMPILED_MODULE_DIR}/_build_config.py" DESTINATION "${PYTHON_PACKAGE_DST_DIR}/pydock/")
foreach(COMPILED_MODULE_PATH ${COMPILED_MODULE_PATH_LIST})
    message(STATUS "INSTALL  ${COMPILED_MODULE_PATH}")
    file(INSTALL ${COMPILED_MODULE_PATH} DESTINATION "${PYTHON_PACKAGE_DST_DIR}/pydock/")
endforeach()
